# Generated by Django 6.0.3 on 2026-04-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
